#!/bin/bash
# ============================================
# Syncs root .env → frontend/.env.local
# Run this after editing .env
# Usage: ./sync-env.sh
# ============================================

set -e

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
FRONTEND_ENV="$ROOT_DIR/frontend/.env.local"

if [ ! -f "$ENV_FILE" ]; then
    echo "❌ .env file not found at $ENV_FILE"
    echo "   Run: cp .env.example .env"
    exit 1
fi

# Source the root .env
set -a
source "$ENV_FILE"
set +a

# Determine WS protocol
if [ "$APP_ENV" = "production" ]; then
    WS_PROTOCOL="wss"
else
    WS_PROTOCOL="ws"
fi

BACKEND_URL="${BACKEND_URL:-http://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-8080}}"
WS_URL="${WS_PROTOCOL}://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-8080}"

cat > "$FRONTEND_ENV" <<EOF
# ============================================
# ⚠️  AUTO-GENERATED by sync-env.sh
# ⚠️  Do NOT edit manually. Edit root .env instead.
# ⚠️  Generated at: $(date)
# ============================================

NEXT_PUBLIC_API_URL=${BACKEND_URL}
NEXT_PUBLIC_WS_URL=${WS_URL}
NEXT_PUBLIC_APP_ENV=${APP_ENV}
EOF

echo "✅ Frontend .env.local synced from root .env"
echo "   API URL:  ${BACKEND_URL}"
echo "   WS URL:   ${WS_URL}"
echo "   APP ENV:  ${APP_ENV}"
